my_blog/blogapp/urls.py
from django.urls import path
from blogapp import views


app_name = 'blogapp'

urlpatterns = [
    path('', views.main_view, name='index'),
    path('post/<int:id>/', views.post, name='post'),
    path('create_post/', views.create_post, name='create_post'),
]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls', namespace='blogapp'))
]

my_blog/blogapp/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    # Id не надо, он уже сам появиться
    name = models.CharField(max_length=16, unique=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    name = models.CharField(max_length=32, unique=True)
    text = models.TextField()
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    # Связь с категорией
    # один - много
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

my_blog/blogapp/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    name = forms.CharField(label='Название поста ',
                           widget=forms.TextInput(attrs={'placeholder': 'Название', 'class': 'form-control'}))

    text = forms.CharField(label='Текст поста',
                         widget=forms.Textarea(attrs={'placeholder': 'Текст поста', 'class': 'form-control'}))

    class Meta:
        model = Post
        fields = '__all__'

my_blog/blogapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from .models import Post
from .forms import PostForm

# Create your views here.
def main_view(request):
    posts = Post.objects.all()
    return render(request, 'blogapp/index.html', context={'posts': posts})

def post(request,id):
    post = Post.objects.get(id=id)
    return render(request, 'blogapp/post.html', context={'post': post})

def create_post(request):
    if request.method == 'GET':
        form = PostForm()
        return render(request, 'blogapp/create_post.html', context={'form': form})
    else:
        form = PostForm(request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('blogapp:index'))
        else:
            return render(request, 'blogapp/create_post.html', context={'form': form})

    return render(request, 'blogapp/create_post.html')

my_blog/blogapp/templates/blogapp/create_post.html
{% extends "base.html" %}
{% block title %} Создать новый пост {% endblock %}
{% block header %} Создать новый пост  {% endblock %}
{% block content %}
        <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}

            <p>{{field}}</p>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>
    </div>
</div>
        {% endblock %}

my_blog/blogapp/templates/blogapp/index.html
{% extends "base.html" %}
{% block title %} Главнвя Страница {% endblock %}
{% block header %} Главнвя Страница {% endblock %}
{% block content %}

    <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        {% for item in posts %}
        <div class="post-preview">
                <a href="{% url 'blogapp:post' id=item.id %}">
                <h2 class="post-title">
                    {{ item.name }}
                </h2>
                </a>
                <h6 class="post-subtitle">
                    {{ item.text }}
                </h6>
            <p class="post-meta">
                {{ item.create }}</p>
        </div>
        <hr>
        {% endfor %}
    </div>
        {% endblock %}

my_blog/blogapp/templates/blogapp/post.html
{% extends "base.html" %}
{% block title %} {{ post.name }} {% endblock %}
{% block header %} {{ post.name }} {% endblock %}
{% block content %}

    <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">

        <div class="post-preview">
                <h2 class="post-title">
                    {{ post.name }}
                </h2>
                <h4 class="post-subtitle">
                    {{ post.category }}
                </h4>
                <h6 class="post-subtitle">
                    {{ post.text }}
                </h6>
            <p class="post-meta">
                {{ post.create }}</p>
        </div>
        <hr>

    </div>
        {% endblock %}

my_blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock %}</title>
        <link rel="icon" type="image/x-icon" href= "{% static 'assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href= "{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blogapp:index' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blogapp:create_post' %}">Sample Post</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url(static/assets/img/home-bg.jpg)">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>{% block header %}{% endblock %}</h1>
                            <span class="subheading">A Blog Theme by Start Bootstrap</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        {% block content %}
         {% endblock %}
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js'%}"></script>
    </body>
</html>